version: "3"

services:
  gradle:
    build:
      dockerfile: Dockerfile.gradlew
      context: .
      args:
        LIFERAY_UID: $UID
    volumes:
      - ./modules:/home/liferay/modules
      - lfr_osgi_modules:/home/liferay/bundles/osgi/modules
  lfr:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        TARGET_ENV: local
        LIFERAY_UID: $UID
    environment:
      - LIFERAY_JPDA_ENABLED=true
    ports:
      - 8080:8080
      - 5005:8000
      - 11311:11311
    volumes:
      - lfr_osgi_modules:/opt/liferay/osgi/modules

volumes:
  lfr_osgi_modules:
